<?php

declare(strict_types=1);

return [
    // =============================================================
    // SUCCÈS FRANÇAIS 2024
    // =============================================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440001',
        'titre'               => 'Un p\'tit truc en plus',
        'description'         => 'Comédie touchante d\'Artus sur le handicap mental. Plus gros succès français 2024 avec 10,8 millions de spectateurs.',
        'duree_minutes'       => 95,
        'categorie'           => 'comedie',
        'realisateur'         => 'Artus',
        'acteurs'             => ['Artus', 'Clovis Cornillac', 'Alice Belaïdi', 'Marc Fraize'],
        'pays_origine'        => 'France',
        'date_sortie'         => '2024-05-01',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=_xXtpZvtXyo',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/aCiCGlnTxawYgWzbS0oYMo4DesF.jpg',
        'tmdb_id'             => 1001,
        'qualites_projection' => ['standard', '4k'],
        'note_moyenne'        => 8.2,
        'nombre_votes'        => 15420,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440002',
        'titre'               => 'Le Comte de Monte-Cristo',
        'description'         => 'Adaptation grandiose du roman d\'Alexandre Dumas avec Pierre Niney. Epic d\'aventure avec 40M€ de budget.',
        'duree_minutes'       => 178,
        'categorie'           => 'aventure',
        'realisateur'         => 'Matthieu Delaporte',
        'acteurs'             => ['Pierre Niney', 'Anaïs Demoustier', 'Bastien Bouillon', 'Anamaria Vartolomei'],
        'pays_origine'        => 'France',
        'date_sortie'         => '2024-06-28',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=u0YnbsyvGS0',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/g7kiprYdXxaYCZABWQwTWAgRYjl.jpg',
        'tmdb_id'             => 1002,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.1,
        'nombre_votes'        => 12800,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440003',
        'titre'               => 'L\'Amour ouf',
        'description'         => 'Drame romantique français intense de Gilles Lellouche.',
        'duree_minutes'       => 143,
        'categorie'           => 'drame',
        'realisateur'         => 'Gilles Lellouche',
        'acteurs'             => ['Adèle Exarchopoulos', 'François Civil', 'Mallory Wanecque', 'Alain Chabat'],
        'pays_origine'        => 'France',
        'date_sortie'         => '2024-10-16',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=bSbA6Aeydbs',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/6akNNv4KyrguZUiG4uemfV6toVq.jpg',
        'tmdb_id'             => 1003,
        'qualites_projection' => ['standard', '4k'],
        'note_moyenne'        => 7.8,
        'nombre_votes'        => 8900,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440004',
        'titre'               => 'Monsieur Aznavour',
        'description'         => 'Biopic sur la vie du célèbre chanteur franco-arménien Charles Aznavour.',
        'duree_minutes'       => 134,
        'categorie'           => 'drame',
        'realisateur'         => 'Mehdi Idir',
        'acteurs'             => ['Tahar Rahim', 'Bastien Bouillon', 'Marie-Julie Baup', 'Petra Silander'],
        'pays_origine'        => 'France',
        'date_sortie'         => '2024-10-23',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=evoYNCdZGOQ',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/23FkaTaAosaTcTgyuJdTf7TvcJu.jpg',
        'tmdb_id'             => 1004,
        'qualites_projection' => ['standard', '4k'],
        'note_moyenne'        => 7.6,
        'nombre_votes'        => 6500,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440005',
        'titre'               => 'Cocorico',
        'description'         => 'Comédie française avec Christian Clavier, Marianne Denicourt, Didier Bourdon et Sylvie Testud.',
        'duree_minutes'       => 98,
        'categorie'           => 'comedie',
        'realisateur'         => 'Julien Hervé',
        'acteurs'             => ['Christian Clavier', 'Marianne Denicourt', 'Didier Bourdon', 'Sylvie Testud'],
        'pays_origine'        => 'France',
        'date_sortie'         => '2024-11-06',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=n6M-AKZBS_Y',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/bH8FlHmk3fYmCsmPvWQ2QbhtSsI.jpg',
        'tmdb_id'             => 1005,
        'qualites_projection' => ['standard'],
        'note_moyenne'        => 6.9,
        'nombre_votes'        => 4200,
    ],

    // =============================================================
    // BLOCKBUSTERS INTERNATIONAUX 2024
    // =============================================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440006',
        'titre'               => 'Vice-Versa 2',
        'description'         => 'Suite de l\'animation Pixar/Disney. 3ème film le plus vu en France 2024 avec 8,4 millions de spectateurs.',
        'duree_minutes'       => 96,
        'categorie'           => 'animation',
        'realisateur'         => 'Kelsey Mann',
        'acteurs'             => ['Amy Poehler', 'Phyllis Smith', 'Lewis Black', 'Diane Lane'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2024-06-14',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=9xoCn6D-PIw',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/9Jic8z9NEeCEmSJFgFHZF1lWMFo.jpg',
        'tmdb_id'             => 1006,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.0,
        'nombre_votes'        => 22000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440007',
        'titre'               => 'Vaiana 2',
        'description'         => 'Suite de l\'animation Disney sur la princesse polynésienne. Plus de 5 millions d\'entrées.',
        'duree_minutes'       => 100,
        'categorie'           => 'animation',
        'realisateur'         => 'David Derrick Jr.',
        'acteurs'             => ['Auliʻi Cravalho', 'Dwayne Johnson', 'Rachel House', 'Temuera Morrison'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2024-11-27',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=Se8ZXbLJUPI',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/usdwoEwm68cdeMOvGFPwSk9nLTr.jpg',
        'tmdb_id'             => 1007,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 7.9,
        'nombre_votes'        => 18500,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440008',
        'titre'               => 'Dune: Deuxième partie',
        'description'         => 'Suite épique de Denis Villeneuve. Experience cinématographique grandiose avec Timothée Chalamet.',
        'duree_minutes'       => 166,
        'categorie'           => 'science_fiction',
        'realisateur'         => 'Denis Villeneuve',
        'acteurs'             => ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Oscar Isaac'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2024-02-28',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=oGimpDBwkFc',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/rBrJl1vUtaM6NU0EwxKSnc3nBxE.jpg',
        'tmdb_id'             => 1008,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.8,
        'nombre_votes'        => 35000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440009',
        'titre'               => 'Deadpool & Wolverine',
        'description'         => 'Rencontre explosif entre Ryan Reynolds et Hugh Jackman. Action, humour et violence assumée.',
        'duree_minutes'       => 128,
        'categorie'           => 'action',
        'realisateur'         => 'Shawn Levy',
        'acteurs'             => ['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin', 'Morena Baccarin'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2024-07-24',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=KT-8QL04x40',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/hw3Gfp8xLpoVewMbFyFVRsqyGlK.jpg',
        'tmdb_id'             => 1009,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.1,
        'nombre_votes'        => 28000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440010',
        'titre'               => 'Gladiator II',
        'description'         => 'Suite épique de Ridley Scott. Retour dans l\'arène avec Paul Mescal et Pedro Pascal.',
        'duree_minutes'       => 148,
        'categorie'           => 'action',
        'realisateur'         => 'Ridley Scott',
        'acteurs'             => ['Paul Mescal', 'Pedro Pascal', 'Denzel Washington', 'Connie Nielsen'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2024-11-22',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=ggVstyjWMR0',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/6YhfdltefsvLvFOPDfATq1b5hE4.jpg',
        'tmdb_id'             => 1010,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.0,
        'nombre_votes'        => 24000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440011',
        'titre'               => 'La Planète des Singes: Le Nouveau Royaume',
        'description'         => 'Nouveau chapitre de la saga. Effets spéciaux époustouflants dans un monde post-apocalyptique.',
        'duree_minutes'       => 145,
        'categorie'           => 'science_fiction',
        'realisateur'         => 'Wes Ball',
        'acteurs'             => ['Owen Teague', 'Freya Allan', 'Kevin Durand', 'Peter Macon'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2024-05-08',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=kF1ADeTeCqY',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/4925wPllJdQmHd1RxbZ62ZekaW3.jpg',
        'tmdb_id'             => 1011,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 7.7,
        'nombre_votes'        => 19000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440012',
        'titre'               => 'Kung Fu Panda 4',
        'description'         => 'Po revient dans une nouvelle aventure animée pleine d\'humour et d\'action.',
        'duree_minutes'       => 94,
        'categorie'           => 'animation',
        'realisateur'         => 'Mike Mitchell',
        'acteurs'             => ['Jack Black', 'Awkwafina', 'Viola Davis', 'Dustin Hoffman'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2024-03-29',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=auCF_IPWb9U',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/y8K9wRRv7YK1ACHqaDlMBrNebVU.jpg',
        'tmdb_id'             => 1012,
        'qualites_projection' => ['standard', '4k', '3d'],
        'note_moyenne'        => 7.4,
        'nombre_votes'        => 16500,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440013',
        'titre'               => 'Moi, Moche et Méchant 4',
        'description'         => 'Gru et ses Minions dans une nouvelle aventure familiale pleine d\'humour.',
        'duree_minutes'       => 95,
        'categorie'           => 'animation',
        'realisateur'         => 'Chris Renaud',
        'acteurs'             => ['Steve Carell', 'Kristen Wiig', 'Pierre Coffin', 'Sofia Vergara'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2024-07-03',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=5HgS6G0xhLY',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/bYovCvLV1RxB0zAR5cXu699P9P7.jpg',
        'tmdb_id'             => 1013,
        'qualites_projection' => ['standard', '4k', '3d'],
        'note_moyenne'        => 7.2,
        'nombre_votes'        => 14000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440014',
        'titre'               => 'Godzilla x Kong: The New Empire',
        'description'         => 'Affrontement titanique entre les deux monstres légendaires. Spectacle visuel grandiose.',
        'duree_minutes'       => 115,
        'categorie'           => 'action',
        'realisateur'         => 'Adam Wingard',
        'acteurs'             => ['Rebecca Hall', 'Brian Cox', 'Dan Stevens', 'Kaylee Hottle'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2024-03-27',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=A_bERKuGCJM',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/nKnWr062zhRvk48NtK27zz3oLgS.jpg',
        'tmdb_id'             => 1014,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax', '3d'],
        'note_moyenne'        => 7.1,
        'nombre_votes'        => 21000,
    ],

    // =============================================================
    // FILMS ATTENDUS 2025 - IMAX & 3D
    // =============================================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440015',
        'titre'               => 'Avatar: Fire and Ash',
        'description'         => 'Troisième opus de James Cameron. Révolution visuelle avec effets 3D époustouflants.',
        'duree_minutes'       => 190,
        'categorie'           => 'science_fiction',
        'realisateur'         => 'James Cameron',
        'acteurs'             => ['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'Stephen Lang'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2025-12-19',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=v6gDsi6dzrM',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/vDdFxksDMkUJjZXd00OKJfwXKre.jpg',
        'tmdb_id'             => 1015,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax', '3d'],
        'note_moyenne'        => 8.9,
        'nombre_votes'        => 45000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440016',
        'titre'               => 'Superman',
        'description'         => 'Nouveau Superman par James Gunn. Tournage avec caméras IMAX certifiées.',
        'duree_minutes'       => 150,
        'categorie'           => 'action',
        'realisateur'         => 'James Gunn',
        'acteurs'             => ['David Corenswet', 'Rachel Brosnahan', 'Nicholas Hoult', 'Edi Gathegi'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2025-07-11',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=zrHUXEctQTc',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/bL1U8TDb2ZiThIBFAdKHOfpv8lk.jpg',
        'tmdb_id'             => 1016,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.5,
        'nombre_votes'        => 32000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440017',
        'titre'               => 'The Fantastic Four: First Steps',
        'description'         => 'Première vraie adaptation des 4 Fantastiques avec Galactus. Univers rétro-futuriste années 60.',
        'duree_minutes'       => 135,
        'categorie'           => 'action',
        'realisateur'         => 'Matt Shakman',
        'acteurs'             => ['Pedro Pascal', 'Vanessa Kirby', 'Joseph Quinn', 'Ebon Moss-Bachrach'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2025-05-02',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=s_FHTwrhytE',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/2REHnvEBsPA121X4Fi8dvGaYJ4o.jpg',
        'tmdb_id'             => 1017,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.2,
        'nombre_votes'        => 28000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440018',
        'titre'               => 'Mission: Impossible – The Final Reckoning',
        'description'         => 'Supposé dernier film d\'Ethan Hunt avec Tom Cruise. Cascades à couper le souffle.',
        'duree_minutes'       => 163,
        'categorie'           => 'action',
        'realisateur'         => 'Christopher McQuarrie',
        'acteurs'             => ['Tom Cruise', 'Hayley Atwell', 'Ving Rhames', 'Simon Pegg'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2025-05-23',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=Si8mScZ-RgY',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/AozMgdALZuR1hDPZt2a1aXiWmL4.jpg',
        'tmdb_id'             => 1018,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.6,
        'nombre_votes'        => 35000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440019',
        'titre'               => 'Jurassic World Rebirth',
        'description'         => 'Nouvelle ère des dinosaures avec Scarlett Johansson. Réalisé par Gareth Edwards.',
        'duree_minutes'       => 147,
        'categorie'           => 'action',
        'realisateur'         => 'Gareth Edwards',
        'acteurs'             => ['Scarlett Johansson', 'Mahershala Ali', 'Jonathan Bailey', 'Rupert Friend'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2025-07-02',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=jan5CFWs9ic',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/uJUzfTtbCUG1GXmVS24h8h0hXX3.jpg',
        'tmdb_id'             => 1019,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax', '3d'],
        'note_moyenne'        => 8.0,
        'nombre_votes'        => 24000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440020',
        'titre'               => 'Wicked: For Good',
        'description'         => 'Suite du succès musical de 2024. L\'un des films IMAX les plus attendus de 2025.',
        'duree_minutes'       => 160,
        'categorie'           => 'musical',
        'realisateur'         => 'Jon M. Chu',
        'acteurs'             => ['Cynthia Erivo', 'Ariana Grande', 'Michelle Yeoh', 'Jeff Goldblum'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2025-11-21',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=kEXOAsdIRPg',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/qEpRUVmn1wWtfiao6FLyeznLyGR.jpg',
        'tmdb_id'             => 1020,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.4,
        'nombre_votes'        => 22000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440021',
        'titre'               => 'Tron: Ares',
        'description'         => 'Retour dans l\'univers digital de Tron. Partie de la slate IMAX 2025.',
        'duree_minutes'       => 125,
        'categorie'           => 'science_fiction',
        'realisateur'         => 'Joachim Rønning',
        'acteurs'             => ['Jared Leto', 'Greta Lee', 'Evan Peters', 'Hasan Minhaj'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2025-10-10',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=9KVG_X_7Naw',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/chpWmskl3aKm1aTZqUHRCtviwPy.jpg',
        'tmdb_id'             => 1021,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 7.9,
        'nombre_votes'        => 18000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440022',
        'titre'               => 'Sinners',
        'description'         => 'Film de Ryan Coogler tourné avec des caméras IMAX. Thriller mystérieux.',
        'duree_minutes'       => 142,
        'categorie'           => 'thriller',
        'realisateur'         => 'Ryan Coogler',
        'acteurs'             => ['Michael B. Jordan', 'Hailee Steinfeld', 'Jack O\'Connell', 'Wunmi Mosaku'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2025-04-18',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=qlkuP6uLf4I',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/9ZmdDOIbiFCZOvRXBQ7muWUu32l.jpg',
        'tmdb_id'             => 1022,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.1,
        'nombre_votes'        => 15000,
    ],

    // =============================================================
    // FILMS DIVERS - MÉLANGES DE GENRES
    // =============================================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440023',
        'titre'               => 'Oppenheimer',
        'description'         => 'Chef-d\'œuvre de Christopher Nolan sur le père de la bombe atomique. Tourné en 70mm IMAX.',
        'duree_minutes'       => 180,
        'categorie'           => 'drame',
        'realisateur'         => 'Christopher Nolan',
        'acteurs'             => ['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.', 'Matt Damon'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2023-07-21',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=CoXtvSRpHgM',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/boAUuJBeID7VNp4L7LNMQs8mfQS.jpg',
        'tmdb_id'             => 1023,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.9,
        'nombre_votes'        => 52000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440024',
        'titre'               => 'Barbie',
        'description'         => 'Comédie rose shocking de Greta Gerwig avec Margot Robbie. Phénomène culturel mondial.',
        'duree_minutes'       => 114,
        'categorie'           => 'comedie',
        'realisateur'         => 'Greta Gerwig',
        'acteurs'             => ['Margot Robbie', 'Ryan Gosling', 'America Ferrera', 'Kate McKinnon'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2023-07-21',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=yK1rMPQ2jBw',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
        'tmdb_id'             => 1024,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.0,
        'nombre_votes'        => 48000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440025',
        'titre'               => 'Spider-Man: Across the Spider-Verse',
        'description'         => 'Animation révolutionnaire sur les multivers. Prouesse technique et artistique.',
        'duree_minutes'       => 140,
        'categorie'           => 'animation',
        'realisateur'         => 'Joaquim Dos Santos',
        'acteurs'             => ['Shameik Moore', 'Hailee Steinfeld', 'Brian Tyree Henry', 'Luna Lauren Velez'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2023-06-02',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=hrCX4trbaNE',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/hvfwCeSTgsExmz9l31dKkfR83DH.jpg',
        'tmdb_id'             => 1025,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.8,
        'nombre_votes'        => 38000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440026',
        'titre'               => 'John Wick: Chapter 4',
        'description'         => 'Quatrième opus de la saga d\'action avec Keanu Reeves. Chorégraphies de combat spectaculaires.',
        'duree_minutes'       => 169,
        'categorie'           => 'action',
        'realisateur'         => 'Chad Stahelski',
        'acteurs'             => ['Keanu Reeves', 'Donnie Yen', 'Bill Skarsgård', 'Laurence Fishburne'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2023-03-24',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=JjBZ2iEBcxM',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/jAMVKvqxdNbUY2YQWhCclYI6coP.jpg',
        'tmdb_id'             => 1026,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.2,
        'nombre_votes'        => 42000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440027',
        'titre'               => 'The Batman',
        'description'         => 'Vision sombre du Chevalier Noir par Matt Reeves avec Robert Pattinson.',
        'duree_minutes'       => 176,
        'categorie'           => 'action',
        'realisateur'         => 'Matt Reeves',
        'acteurs'             => ['Robert Pattinson', 'Zoë Kravitz', 'Paul Dano', 'Jeffrey Wright'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2022-03-04',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=adJ9r7V5GfA',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/t9JGg10CW1DzXEdWL54ewkUko6N.jpg',
        'tmdb_id'             => 1027,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.1,
        'nombre_votes'        => 36000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440028',
        'titre'               => 'Top Gun: Maverick',
        'description'         => 'Suite légendaire avec Tom Cruise. Séquences aériennes époustouflantes tournées en IMAX.',
        'duree_minutes'       => 130,
        'categorie'           => 'action',
        'realisateur'         => 'Joseph Kosinski',
        'acteurs'             => ['Tom Cruise', 'Miles Teller', 'Jennifer Connelly', 'Jon Hamm'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2022-05-27',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=V4gQdk1nAn0',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/kTh1s6I6yUyk2OGiRoGkDTYTS6K.jpg',
        'tmdb_id'             => 1028,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.7,
        'nombre_votes'        => 44000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440029',
        'titre'               => 'Avengers: Endgame',
        'description'         => 'Conclusion épique de la saga Marvel. Spectacle à l\'échelle cosmique.',
        'duree_minutes'       => 181,
        'categorie'           => 'action',
        'realisateur'         => 'Anthony Russo',
        'acteurs'             => ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2019-04-26',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=jTC2fgxMwxU',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/wF7jv3x51hXgkl7t5KHePuRjXc8.jpg',
        'tmdb_id'             => 1029,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax', '3d'],
        'note_moyenne'        => 8.6,
        'nombre_votes'        => 58000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440030',
        'titre'               => 'Interstellar',
        'description'         => 'Chef-d\'œuvre de science-fiction de Christopher Nolan. Voyage spatial transcendant.',
        'duree_minutes'       => 169,
        'categorie'           => 'science_fiction',
        'realisateur'         => 'Christopher Nolan',
        'acteurs'             => ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2014-11-07',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=kTGDxqUowq4',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/1pnigkWWy8W032o9TKDneBa3eVK.jpg',
        'tmdb_id'             => 1030,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.9,
        'nombre_votes'        => 65000,
    ],

    // =============================================================
    // FILMS FRANÇAIS RÉCENTS & CLASSIQUES
    // =============================================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440031',
        'titre'               => 'Le Fabuleux Destin d\'Amélie Poulain',
        'description'         => 'Chef-d\'œuvre français de Jean-Pierre Jeunet. Poésie visuelle et tendresse parisienne.',
        'duree_minutes'       => 122,
        'categorie'           => 'comedie',
        'realisateur'         => 'Jean-Pierre Jeunet',
        'acteurs'             => ['Audrey Tautou', 'Mathieu Kassovitz', 'Rufus', 'Lorella Cravotta'],
        'pays_origine'        => 'France',
        'date_sortie'         => '2001-04-25',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=_cZyjM_R6-E',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/tdXtLG6L1QMwrv0MNdW6B9IwC8B.jpg',
        'tmdb_id'             => 1031,
        'qualites_projection' => ['standard', '4k'],
        'note_moyenne'        => 8.8,
        'nombre_votes'        => 48000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440032',
        'titre'               => 'Intouchables',
        'description'         => 'Comédie dramatique française avec François Cluzet et Omar Sy. Succès international.',
        'duree_minutes'       => 112,
        'categorie'           => 'comedie',
        'realisateur'         => 'Olivier Nakache',
        'acteurs'             => ['François Cluzet', 'Omar Sy', 'Anne Le Ny', 'Audrey Fleurot'],
        'pays_origine'        => 'France',
        'date_sortie'         => '2011-11-02',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=cXu2MhWYUuE',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/gdUJ6ECIHNE5M2HImGaBOfb8jR2.jpg',
        'tmdb_id'             => 1032,
        'qualites_projection' => ['standard', '4k'],
        'note_moyenne'        => 8.7,
        'nombre_votes'        => 35000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440033',
        'titre'               => 'La Haine',
        'description'         => 'Drame social culte de Mathieu Kassovitz. Portrait saisissant des banlieues françaises.',
        'duree_minutes'       => 98,
        'categorie'           => 'drame',
        'realisateur'         => 'Mathieu Kassovitz',
        'acteurs'             => ['Vincent Cassel', 'Hubert Koundé', 'Saïd Taghmaoui', 'Abdel Ahmed Ghili'],
        'pays_origine'        => 'France',
        'date_sortie'         => '1995-05-31',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=G65Y-yr4M4o',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/gfdhSzPyAWtAizqs4ytc0MwOlQg.jpg',
        'tmdb_id'             => 1033,
        'qualites_projection' => ['standard', '4k'],
        'note_moyenne'        => 8.5,
        'nombre_votes'        => 28000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440034',
        'titre'               => 'Taxi',
        'description'         => 'Comédie d\'action française culte de Luc Besson avec Samy Naceri et Frédéric Diefenthal.',
        'duree_minutes'       => 89,
        'categorie'           => 'action',
        'realisateur'         => 'Gérard Pirès',
        'acteurs'             => ['Samy Naceri', 'Frédéric Diefenthal', 'Marion Cotillard', 'Manuela Gourary'],
        'pays_origine'        => 'France',
        'date_sortie'         => '1998-04-08',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=Ulhfx2yItH4',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/5d16tJ2DLImAwCY2w0LYZjgWZA1.jpg',
        'tmdb_id'             => 1034,
        'qualites_projection' => ['standard', '4k'],
        'note_moyenne'        => 7.3,
        'nombre_votes'        => 22000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440035',
        'titre'               => 'Astérix & Obélix: Mission Cléopâtre',
        'description'         => 'Adaptation déjantée d\'Alain Chabat. Comédie française familiale culte.',
        'duree_minutes'       => 107,
        'categorie'           => 'comedie',
        'realisateur'         => 'Alain Chabat',
        'acteurs'             => ['Christian Clavier', 'Gérard Depardieu', 'Jamel Debbouze', 'Monica Bellucci'],
        'pays_origine'        => 'France',
        'date_sortie'         => '2002-01-30',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=iT1n9Z4hVuk',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/2lC9lzozlzVxCsSgPjRz5AWcz00.jpg',
        'tmdb_id'             => 1035,
        'qualites_projection' => ['standard', '4k'],
        'note_moyenne'        => 7.8,
        'nombre_votes'        => 25000,
    ],

    // =============================================================
    // FILMS HORREUR & THRILLER
    // =============================================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440036',
        'titre'               => 'Hereditary',
        'description'         => 'Film d\'horreur psychologique terrifiant d\'Ari Aster. Angoisse pure et performances magistrales.',
        'duree_minutes'       => 127,
        'categorie'           => 'horreur',
        'realisateur'         => 'Ari Aster',
        'acteurs'             => ['Toni Collette', 'Alex Wolff', 'Milly Shapiro', 'Gabriel Byrne'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2018-06-08',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=7P_L9oJ9SzQ',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/5Bz0u7xEyOUnGi4ov3rZKqKYCuH.jpg',
        'tmdb_id'             => 1036,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.0,
        'nombre_votes'        => 32000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440037',
        'titre'               => 'Get Out',
        'description'         => 'Thriller social révolutionnaire de Jordan Peele. Horreur et critique sociale brillante.',
        'duree_minutes'       => 104,
        'categorie'           => 'thriller',
        'realisateur'         => 'Jordan Peele',
        'acteurs'             => ['Daniel Kaluuya', 'Allison Williams', 'Lil Rel Howery', 'Bradley Whitford'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2017-02-24',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=XzmeT5rEPDg',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/8WzjAhgc4HvpN3Y6LLCc6AbpIhF.jpg',
        'tmdb_id'             => 1037,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.1,
        'nombre_votes'        => 28000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440038',
        'titre'               => 'Sans un bruit',
        'description'         => 'Thriller post-apocalyptique novateur de John Krasinski. Silence et tension extrême.',
        'duree_minutes'       => 90,
        'categorie'           => 'thriller',
        'realisateur'         => 'John Krasinski',
        'acteurs'             => ['Emily Blunt', 'John Krasinski', 'Millicent Simmonds', 'Noah Jupe'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2018-04-06',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=XJUUK62vv9g',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/S3PKmsBviNmXDYmik7uanIqpzD.jpg',
        'tmdb_id'             => 1038,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 7.9,
        'nombre_votes'        => 24000,
    ],

    // =============================================================
    // FILMS DRAMES & ROMANCE
    // =============================================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440039',
        'titre'               => 'Parasite',
        'description'         => 'Chef-d\'œuvre coréen de Bong Joon-ho. Thriller social Palme d\'Or et Oscar du meilleur film.',
        'duree_minutes'       => 132,
        'categorie'           => 'drame',
        'realisateur'         => 'Bong Joon-ho',
        'acteurs'             => ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik'],
        'pays_origine'        => 'Corée du Sud',
        'date_sortie'         => '2019-05-30',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=_YD8WKEZaPo',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/7hLSzZX2jROmEXz2aEoh6JKUFy2.jpg',
        'tmdb_id'             => 1039,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.8,
        'nombre_votes'        => 42000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440040',
        'titre'               => 'La La Land',
        'description'         => 'Comédie musicale romantique de Damien Chazelle. Rêve américain et amour à Los Angeles.',
        'duree_minutes'       => 128,
        'categorie'           => 'musical',
        'realisateur'         => 'Damien Chazelle',
        'acteurs'             => ['Ryan Gosling', 'Emma Stone', 'John Legend', 'Rosemarie DeWitt'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2016-12-09',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=vOBtJWG_KlI',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/5KIj6aioW1UtUT1IV0qqW5iZbNH.jpg',
        'tmdb_id'             => 1040,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.4,
        'nombre_votes'        => 38000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440041',
        'titre'               => 'Marriage Story',
        'description'         => 'Drame intimiste de Noah Baumbach sur un divorce. Performances bouleversantes.',
        'duree_minutes'       => 137,
        'categorie'           => 'drame',
        'realisateur'         => 'Noah Baumbach',
        'acteurs'             => ['Adam Driver', 'Scarlett Johansson', 'Laura Dern', 'Alan Alda'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2019-11-06',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=V591lwbrrlI',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/kYGvkQpq6yibGTMp7LcauV0fnc8.jpg',
        'tmdb_id'             => 1041,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.2,
        'nombre_votes'        => 26000,
    ],

    // =============================================================
    // FILMS DOCUMENTAIRES
    // =============================================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440042',
        'titre'               => 'Free Solo',
        'description'         => 'Documentaire époustouflant sur l\'escalade d\'Alex Honnold. Vertige et dépassement de soi.',
        'duree_minutes'       => 100,
        'categorie'           => 'documentaire',
        'realisateur'         => 'Jimmy Chin',
        'acteurs'             => ['Alex Honnold', 'Tommy Caldwell', 'Sanni McCandless'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2018-09-28',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=xpDQTWVVRK4',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/v4QfYZMACODlWul9doN9RxE99ag.jpg',
        'tmdb_id'             => 1042,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.3,
        'nombre_votes'        => 18000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440043',
        'titre'               => 'Won\'t You Be My Neighbor?',
        'description'         => 'Documentaire touchant sur Fred Rogers et son émission pour enfants.',
        'duree_minutes'       => 94,
        'categorie'           => 'documentaire',
        'realisateur'         => 'Morgan Neville',
        'acteurs'             => ['Fred Rogers', 'Joanne Rogers', 'François Clemmons'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2018-06-08',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=EAwR54HrVW8',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/8qE8NZjiP2M884baH0VoLF828Vp.jpg',
        'tmdb_id'             => 1043,
        'qualites_projection' => ['standard', '4k'],
        'note_moyenne'        => 8.1,
        'nombre_votes'        => 12000,
    ],

    // =============================================================
    // FILMS FANTASTIQUE & AVENTURE
    // =============================================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440044',
        'titre'               => 'Le Seigneur des Anneaux: Le Retour du Roi',
        'description'         => 'Épique conclusion de la trilogie de Peter Jackson. Fantasy monumentale et émouvante.',
        'duree_minutes'       => 201,
        'categorie'           => 'fantastique',
        'realisateur'         => 'Peter Jackson',
        'acteurs'             => ['Elijah Wood', 'Viggo Mortensen', 'Ian McKellen', 'Sean Astin'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2003-12-17',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=HQRTu6kgvmU',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/aqiFUqswXVM58Tamux1ilnNvVRs.jpg',
        'tmdb_id'             => 1044,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 9.0,
        'nombre_votes'        => 68000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440045',
        'titre'               => 'Harry Potter à l\'École des Sorciers',
        'description'         => 'Premier volet de la saga magique de J.K. Rowling. Début d\'une aventure légendaire.',
        'duree_minutes'       => 152,
        'categorie'           => 'fantastique',
        'realisateur'         => 'Chris Columbus',
        'acteurs'             => ['Daniel Radcliffe', 'Emma Watson', 'Rupert Grint', 'Alan Rickman'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2001-11-16',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=UMs6IqPievo',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/fbxQ44VRdM2PVzHSNajUseUteem.jpg',
        'tmdb_id'             => 1045,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.5,
        'nombre_votes'        => 55000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440046',
        'titre'               => 'Indiana Jones: Les Aventuriers de l\'Arche Perdue',
        'description'         => 'Aventure classique de Spielberg et Lucas. Archéologue héroïque et action pure.',
        'duree_minutes'       => 115,
        'categorie'           => 'aventure',
        'realisateur'         => 'Steven Spielberg',
        'acteurs'             => ['Harrison Ford', 'Karen Allen', 'Paul Freeman', 'Ronald Lacey'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '1981-06-12',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=JdKKkWHx8pQ',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/nTsllJhHBDZndFudSB2RgeHuQAt.jpg',
        'tmdb_id'             => 1046,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.7,
        'nombre_votes'        => 48000,
    ],

    // =============================================================
    // FILMS WESTERN & DIVERS
    // =============================================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440047',
        'titre'               => 'Django Unchained',
        'description'         => 'Western brutal et stylisé de Quentin Tarantino. Vengeance et justice dans le Sud américain.',
        'duree_minutes'       => 165,
        'categorie'           => 'western',
        'realisateur'         => 'Quentin Tarantino',
        'acteurs'             => ['Jamie Foxx', 'Christoph Waltz', 'Leonardo DiCaprio', 'Kerry Washington'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2012-12-25',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=K2XjgsfzDrU',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/hodO0759IB5LbzUiiLKB50gT2UO.jpg',
        'tmdb_id'             => 1047,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.6,
        'nombre_votes'        => 41000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440048',
        'titre'               => 'Mad Max: Fury Road',
        'description'         => 'Chef-d\'œuvre post-apocalyptique de George Miller. Action pure et visuels époustouflants.',
        'duree_minutes'       => 120,
        'categorie'           => 'action',
        'realisateur'         => 'George Miller',
        'acteurs'             => ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult', 'Hugh Keays-Byrne'],
        'pays_origine'        => 'Australie',
        'date_sortie'         => '2015-05-15',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=3rk7lkEUiuY',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/oLy2V6AWSEfdPgKOtrSGnwB3Q2R.jpg',
        'tmdb_id'             => 1048,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.4,
        'nombre_votes'        => 38000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440049',
        'titre'               => 'Blade Runner 2049',
        'description'         => 'Suite magistrale de Denis Villeneuve. Science-fiction contemplative et visuellement parfaite.',
        'duree_minutes'       => 164,
        'categorie'           => 'science_fiction',
        'realisateur'         => 'Denis Villeneuve',
        'acteurs'             => ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas', 'Jared Leto'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2017-10-06',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=R9WlM3lAJok',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/baCC3v1wLnmoBbr2aH0e7P312gv.jpg',
        'tmdb_id'             => 1049,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.3,
        'nombre_votes'        => 34000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440050',
        'titre'               => 'Joker',
        'description'         => 'Origine sombre du célèbre vilain par Todd Phillips. Performance légendaire de Joaquin Phoenix.',
        'duree_minutes'       => 122,
        'categorie'           => 'drame',
        'realisateur'         => 'Todd Phillips',
        'acteurs'             => ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz', 'Frances Conroy'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2019-10-04',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=_LUWnjT3iks',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/tWjJ3ILjsbTwKgXxEv48QAbYZ19.jpg',
        'tmdb_id'             => 1050,
        'qualites_projection' => ['standard', '4k', 'hdr', 'imax'],
        'note_moyenne'        => 8.5,
        'nombre_votes'        => 46000,
    ],

    // =============================================================
    // FILMS MANQUANTS - CATÉGORIES SOUS-REPRÉSENTÉES
    // =============================================================

    // ROMANCE (0 films -> 2 films)
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440051',
        'titre'               => 'Titanic',
        'description'         => 'Romance épique de James Cameron. Histoire d\'amour tragique sur le célèbre paquebot.',
        'duree_minutes'       => 195,
        'categorie'           => 'romance',
        'realisateur'         => 'James Cameron',
        'acteurs'             => ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane', 'Gloria Stuart'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '1997-12-19',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=Quf4qIkD3KY',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/vpsvHLkoeKUjceIMeNSqCp3xEyY.jpg',
        'tmdb_id'             => 1051,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.8,
        'nombre_votes'        => 82000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440052',
        'titre'               => 'N\'oublie jamais',
        'description'         => 'Romance touchante avec Ryan Gosling et Rachel McAdams. Amour éternel et souvenirs.',
        'duree_minutes'       => 123,
        'categorie'           => 'romance',
        'realisateur'         => 'Nick Cassavetes',
        'acteurs'             => ['Ryan Gosling', 'Rachel McAdams', 'James Garner', 'Gena Rowlands'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2004-06-25',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=dC9Zq8uWcnw',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/sP5f85ziKthDrAyXOwoBlnpPmNv.jpg',
        'tmdb_id'             => 1052,
        'qualites_projection' => ['standard', '4k'],
        'note_moyenne'        => 8.1,
        'nombre_votes'        => 45000,
    ],

    // HISTORIQUE (0 films -> 2 films)
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440053',
        'titre'               => 'Gladiator',
        'description'         => 'Épopée historique de Ridley Scott dans la Rome antique. Russell Crowe légendaire.',
        'duree_minutes'       => 155,
        'categorie'           => 'historique',
        'realisateur'         => 'Ridley Scott',
        'acteurs'             => ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen', 'Oliver Reed'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2000-05-05',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=Nz5CnNHnpO8',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/3fDI4D5rWefyUs7kLcvyafwBEmZ.jpg',
        'tmdb_id'             => 1053,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.9,
        'nombre_votes'        => 78000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440054',
        'titre'               => 'Braveheart',
        'description'         => 'Épopée médiévale de Mel Gibson. William Wallace et l\'indépendance écossaise.',
        'duree_minutes'       => 178,
        'categorie'           => 'historique',
        'realisateur'         => 'Mel Gibson',
        'acteurs'             => ['Mel Gibson', 'Sophie Marceau', 'Patrick McGoohan', 'Catherine McCormack'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '1995-05-24',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=ePBRBuYEuHk',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/cteCb7HgeNmx8aeu5drpTb7N8fB.jpg',
        'tmdb_id'             => 1054,
        'qualites_projection' => ['standard', '4k'],
        'note_moyenne'        => 8.6,
        'nombre_votes'        => 65000,
    ],

    // POLICIER (0 films -> 2 films)
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440055',
        'titre'               => 'Heat',
        'description'         => 'Chef-d\'œuvre policier de Michael Mann. Duel De Niro vs Pacino dans Los Angeles.',
        'duree_minutes'       => 170,
        'categorie'           => 'policier',
        'realisateur'         => 'Michael Mann',
        'acteurs'             => ['Al Pacino', 'Robert De Niro', 'Val Kilmer', 'Jon Voight'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '1995-12-15',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=Xl7X4Pf3PTY',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/e0xv5Y7UVrhKEVy1g3URMLLVDYB.jpg',
        'tmdb_id'             => 1055,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.7,
        'nombre_votes'        => 52000,
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440056',
        'titre'               => 'Seven',
        'description'         => 'Thriller policier sombre de David Fincher. Enquête sur les sept péchés capitaux.',
        'duree_minutes'       => 127,
        'categorie'           => 'policier',
        'realisateur'         => 'David Fincher',
        'acteurs'             => ['Brad Pitt', 'Morgan Freeman', 'Gwyneth Paltrow', 'Kevin Spacey'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '1995-09-22',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=X4SAjaHFeDw',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/upIOOLVeOoUkTM5fVWwXW2JmBrW.jpg',
        'tmdb_id'             => 1056,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.8,
        'nombre_votes'        => 68000,
    ],

    // HORREUR (1 film -> 2 films)
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440057',
        'titre'               => 'The Conjuring',
        'description'         => 'Film d\'horreur moderne de James Wan. Paranormal et épouvante pure.',
        'duree_minutes'       => 112,
        'categorie'           => 'horreur',
        'realisateur'         => 'James Wan',
        'acteurs'             => ['Vera Farmiga', 'Patrick Wilson', 'Lili Taylor', 'Ron Livingston'],
        'pays_origine'        => 'États-Unis',
        'date_sortie'         => '2013-07-19',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=McOmzgX09wo',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/vOnTvcSsxdJWL9xgauljHHmFSN4.jpg',
        'tmdb_id'             => 1057,
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'note_moyenne'        => 8.0,
        'nombre_votes'        => 35000,
    ],

    // WESTERN (1 film -> 2 films)
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440058',
        'titre'               => 'Le Bon, la Brute et le Truand',
        'description'         => 'Chef-d\'œuvre western de Sergio Leone. Clint Eastwood dans l\'Ouest sauvage.',
        'duree_minutes'       => 161,
        'categorie'           => 'western',
        'realisateur'         => 'Sergio Leone',
        'acteurs'             => ['Clint Eastwood', 'Lee Van Cleef', 'Eli Wallach', 'Aldo Giuffrè'],
        'pays_origine'        => 'Italie',
        'date_sortie'         => '1966-12-23',
        'bande_annonce_url'   => 'https://www.youtube.com/watch?v=WA1hCZFOPqs',
        'affiche_url'         => 'https://media.themoviedb.org/t/p/original/qEr65B4yGlsmLQjcM0xjSUMfZS2.jpg',
        'tmdb_id'             => 1058,
        'qualites_projection' => ['standard', '4k'],
        'note_moyenne'        => 9.1,
        'nombre_votes'        => 48000,
    ],
];
