<?php

declare(strict_types=1);

return [
    // ==========================================
    // CINÉPHORIA CHÂTELET - 8 salles
    // UUID: 550e8400-e29b-41d4-a716-446655440001
    // ==========================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440101',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440001',
        'numero'              => '1',
        'nom'                 => 'Salle Méliès',
        'capacite'            => 180,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['3D', 'dolby_atmos', 'fauteuils_cuir'],
        'plan_salle'          => [
            'rangees'           => 12,
            'sieges_par_rangee' => 15,
            'allees'            => 2,
            'pmr'               => 4,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440102',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440001',
        'numero'              => '2',
        'nom'                 => 'Salle Lumière',
        'capacite'            => 220,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k', 'hdr'],
        'equipements'         => ['3D', 'dolby_atmos', 'fauteuils_premium'],
        'plan_salle'          => [
            'rangees'           => 14,
            'sieges_par_rangee' => 16,
            'allees'            => 2,
            'pmr'               => 6,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440103',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440001',
        'numero'              => '3',
        'nom'                 => 'Salle Godard',
        'capacite'            => 150,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 10,
            'sieges_par_rangee' => 15,
            'allees'            => 2,
            'pmr'               => 3,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440104',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440001',
        'numero'              => '4',
        'nom'                 => 'Salle Truffaut',
        'capacite'            => 120,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 15,
            'allees'            => 2,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440105',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440001',
        'numero'              => '5',
        'nom'                 => 'Salle Renoir',
        'capacite'            => 100,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 12,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440106',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440001',
        'numero'              => '6',
        'nom'                 => 'Salle Rohmer',
        'capacite'            => 80,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 6,
            'sieges_par_rangee' => 13,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440107',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440001',
        'numero'              => '7',
        'nom'                 => 'Salle Varda',
        'capacite'            => 60,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 5,
            'sieges_par_rangee' => 12,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440108',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440001',
        'numero'              => '8',
        'nom'                 => 'Salle Demy',
        'capacite'            => 40,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard'],
        'plan_salle'          => [
            'rangees'           => 4,
            'sieges_par_rangee' => 10,
            'allees'            => 1,
            'pmr'               => 1,
        ],
    ],

    // ==========================================
    // CINÉPHORIA LA DÉFENSE - 10 salles
    // UUID: 550e8400-e29b-41d4-a716-446655440002
    // ==========================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440201',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440002',
        'numero'              => '1',
        'nom'                 => 'Salle IMAX',
        'capacite'            => 400,
        'etat'                => 'active',
        'qualites_projection' => ['imax', '4k', 'hdr'],
        'equipements'         => ['imax', '3D', 'dolby_atmos', 'fauteuils_premium'],
        'plan_salle'          => [
            'rangees'           => 20,
            'sieges_par_rangee' => 20,
            'allees'            => 3,
            'pmr'               => 8,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440202',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440002',
        'numero'              => '2',
        'nom'                 => 'Salle Premium',
        'capacite'            => 300,
        'etat'                => 'active',
        'qualites_projection' => ['4k', 'hdr'],
        'equipements'         => ['3D', 'dolby_atmos', 'fauteuils_premium', 'service_table'],
        'plan_salle'          => [
            'rangees'           => 15,
            'sieges_par_rangee' => 20,
            'allees'            => 3,
            'pmr'               => 6,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440203',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440002',
        'numero'              => '3',
        'nom'                 => 'Salle Alpha',
        'capacite'            => 250,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['3D', 'dolby_atmos', 'fauteuils_cuir'],
        'plan_salle'          => [
            'rangees'           => 12,
            'sieges_par_rangee' => 21,
            'allees'            => 2,
            'pmr'               => 5,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440204',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440002',
        'numero'              => '4',
        'nom'                 => 'Salle Beta',
        'capacite'            => 250,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['3D', 'dolby_atmos', 'fauteuils_cuir'],
        'plan_salle'          => [
            'rangees'           => 12,
            'sieges_par_rangee' => 21,
            'allees'            => 2,
            'pmr'               => 5,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440205',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440002',
        'numero'              => '5',
        'nom'                 => 'Salle Gamma',
        'capacite'            => 200,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['3D', 'fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 10,
            'sieges_par_rangee' => 20,
            'allees'            => 2,
            'pmr'               => 4,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440206',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440002',
        'numero'              => '6',
        'nom'                 => 'Salle Delta',
        'capacite'            => 200,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['3D', 'fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 10,
            'sieges_par_rangee' => 20,
            'allees'            => 2,
            'pmr'               => 4,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440207',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440002',
        'numero'              => '7',
        'nom'                 => 'Salle Epsilon',
        'capacite'            => 150,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 19,
            'allees'            => 2,
            'pmr'               => 3,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440208',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440002',
        'numero'              => '8',
        'nom'                 => 'Salle Zeta',
        'capacite'            => 150,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 19,
            'allees'            => 2,
            'pmr'               => 3,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440209',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440002',
        'numero'              => '9',
        'nom'                 => 'Salle Eta',
        'capacite'            => 120,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 15,
            'allees'            => 2,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440210',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440002',
        'numero'              => '10',
        'nom'                 => 'Salle Theta',
        'capacite'            => 100,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 12,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],

    // ==========================================
    // CINÉPHORIA LYON - 7 salles
    // UUID: 550e8400-e29b-41d4-a716-446655440003
    // ==========================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440301',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440003',
        'numero'              => '1',
        'nom'                 => 'Salle Presqu\'île',
        'capacite'            => 200,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['3D', 'dolby_atmos', 'fauteuils_cuir'],
        'plan_salle'          => [
            'rangees'           => 10,
            'sieges_par_rangee' => 20,
            'allees'            => 2,
            'pmr'               => 4,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440302',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440003',
        'numero'              => '2',
        'nom'                 => 'Salle Bellecour',
        'capacite'            => 180,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['3D', 'fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 9,
            'sieges_par_rangee' => 20,
            'allees'            => 2,
            'pmr'               => 4,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440303',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440003',
        'numero'              => '3',
        'nom'                 => 'Salle Croix-Rousse',
        'capacite'            => 150,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 19,
            'allees'            => 2,
            'pmr'               => 3,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440304',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440003',
        'numero'              => '4',
        'nom'                 => 'Salle Vieux-Lyon',
        'capacite'            => 120,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 15,
            'allees'            => 2,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440305',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440003',
        'numero'              => '5',
        'nom'                 => 'Salle Confluence',
        'capacite'            => 100,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 12,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440306',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440003',
        'numero'              => '6',
        'nom'                 => 'Salle Part-Dieu',
        'capacite'            => 80,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 6,
            'sieges_par_rangee' => 13,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440307',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440003',
        'numero'              => '7',
        'nom'                 => 'Salle Fourvière',
        'capacite'            => 60,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard'],
        'plan_salle'          => [
            'rangees'           => 5,
            'sieges_par_rangee' => 12,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],

    // ==========================================
    // CINÉPHORIA MARSEILLE - 6 salles
    // UUID: 550e8400-e29b-41d4-a716-446655440004
    // ==========================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440401',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440004',
        'numero'              => '1',
        'nom'                 => 'Salle Vieux-Port',
        'capacite'            => 220,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['3D', 'dolby_atmos', 'fauteuils_cuir', 'vue_mer'],
        'plan_salle'          => [
            'rangees'           => 11,
            'sieges_par_rangee' => 20,
            'allees'            => 2,
            'pmr'               => 4,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440402',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440004',
        'numero'              => '2',
        'nom'                 => 'Salle Canebière',
        'capacite'            => 180,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['3D', 'fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 9,
            'sieges_par_rangee' => 20,
            'allees'            => 2,
            'pmr'               => 4,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440403',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440004',
        'numero'              => '3',
        'nom'                 => 'Salle Notre-Dame',
        'capacite'            => 150,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 19,
            'allees'            => 2,
            'pmr'               => 3,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440404',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440004',
        'numero'              => '4',
        'nom'                 => 'Salle Panier',
        'capacite'            => 120,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 15,
            'allees'            => 2,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440405',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440004',
        'numero'              => '5',
        'nom'                 => 'Salle Corniche',
        'capacite'            => 100,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation', 'terrasse'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 12,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440406',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440004',
        'numero'              => '6',
        'nom'                 => 'Salle Calanques',
        'capacite'            => 80,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 6,
            'sieges_par_rangee' => 13,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],

    // ==========================================
    // CINÉPHORIA BRUXELLES - 9 salles
    // UUID: 550e8400-e29b-41d4-a716-446655440005
    // ==========================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440501',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440005',
        'numero'              => '1',
        'nom'                 => 'Salle Grand-Place',
        'capacite'            => 250,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['3D', 'dolby_atmos', 'fauteuils_premium'],
        'plan_salle'          => [
            'rangees'           => 12,
            'sieges_par_rangee' => 21,
            'allees'            => 2,
            'pmr'               => 5,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440502',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440005',
        'numero'              => '2',
        'nom'                 => 'Salle Atomium',
        'capacite'            => 200,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['3D', 'fauteuils_cuir', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 10,
            'sieges_par_rangee' => 20,
            'allees'            => 2,
            'pmr'               => 4,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440503',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440005',
        'numero'              => '3',
        'nom'                 => 'Salle Manneken-Pis',
        'capacite'            => 180,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 9,
            'sieges_par_rangee' => 20,
            'allees'            => 2,
            'pmr'               => 4,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440504',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440005',
        'numero'              => '4',
        'nom'                 => 'Salle Sablon',
        'capacite'            => 150,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 19,
            'allees'            => 2,
            'pmr'               => 3,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440505',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440005',
        'numero'              => '5',
        'nom'                 => 'Salle Marolles',
        'capacite'            => 120,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 15,
            'allees'            => 2,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440506',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440005',
        'numero'              => '6',
        'nom'                 => 'Salle Ixelles',
        'capacite'            => 100,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 12,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440507',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440005',
        'numero'              => '7',
        'nom'                 => 'Salle Etterbeek',
        'capacite'            => 80,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 6,
            'sieges_par_rangee' => 13,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440508',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440005',
        'numero'              => '8',
        'nom'                 => 'Salle Uccle',
        'capacite'            => 60,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard'],
        'plan_salle'          => [
            'rangees'           => 5,
            'sieges_par_rangee' => 12,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440509',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440005',
        'numero'              => '9',
        'nom'                 => 'Salle Laeken',
        'capacite'            => 40,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard'],
        'plan_salle'          => [
            'rangees'           => 4,
            'sieges_par_rangee' => 10,
            'allees'            => 1,
            'pmr'               => 1,
        ],
    ],

    // ==========================================
    // CINÉPHORIA BORDEAUX - 8 salles
    // UUID: 550e8400-e29b-41d4-a716-446655440006
    // ==========================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440601',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440006',
        'numero'              => '1',
        'nom'                 => 'Salle Garonne',
        'capacite'            => 240,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['3D', 'dolby_atmos', 'fauteuils_cuir'],
        'plan_salle'          => [
            'rangees'           => 12,
            'sieges_par_rangee' => 20,
            'allees'            => 2,
            'pmr'               => 5,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440602',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440006',
        'numero'              => '2',
        'nom'                 => 'Salle Mériadeck',
        'capacite'            => 200,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['3D', 'fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 10,
            'sieges_par_rangee' => 20,
            'allees'            => 2,
            'pmr'               => 4,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440603',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440006',
        'numero'              => '3',
        'nom'                 => 'Salle Saint-Pierre',
        'capacite'            => 150,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 19,
            'allees'            => 2,
            'pmr'               => 3,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440604',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440006',
        'numero'              => '4',
        'nom'                 => 'Salle Bastide',
        'capacite'            => 120,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 15,
            'allees'            => 2,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440605',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440006',
        'numero'              => '5',
        'nom'                 => 'Salle Chartrons',
        'capacite'            => 100,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 12,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440606',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440006',
        'numero'              => '6',
        'nom'                 => 'Salle Caudéran',
        'capacite'            => 80,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 6,
            'sieges_par_rangee' => 13,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440607',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440006',
        'numero'              => '7',
        'nom'                 => 'Salle Pessac',
        'capacite'            => 60,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard'],
        'plan_salle'          => [
            'rangees'           => 5,
            'sieges_par_rangee' => 12,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440608',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440006',
        'numero'              => '8',
        'nom'                 => 'Salle Mérignac',
        'capacite'            => 40,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_standard'],
        'plan_salle'          => [
            'rangees'           => 4,
            'sieges_par_rangee' => 10,
            'allees'            => 1,
            'pmr'               => 1,
        ],
    ],

    // ==========================================
    // CINÉPHORIA TOULOUSE - 6 salles
    // UUID: 550e8400-e29b-41d4-a716-446655440007
    // ==========================================
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440701',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440007',
        'numero'              => '1',
        'nom'                 => 'Salle Capitole',
        'capacite'            => 200,
        'etat'                => 'active',
        'qualites_projection' => ['standard', '4k'],
        'equipements'         => ['3D', 'dolby_atmos', 'fauteuils_heritage'],
        'plan_salle'          => [
            'rangees'           => 10,
            'sieges_par_rangee' => 20,
            'allees'            => 2,
            'pmr'               => 4,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440702',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440007',
        'numero'              => '2',
        'nom'                 => 'Salle Wilson',
        'capacite'            => 150,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_heritage', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 19,
            'allees'            => 2,
            'pmr'               => 3,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440703',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440007',
        'numero'              => '3',
        'nom'                 => 'Salle Esquirol',
        'capacite'            => 120,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_heritage', 'climatisation'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 15,
            'allees'            => 2,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440704',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440007',
        'numero'              => '4',
        'nom'                 => 'Salle Jeanne-d\'Arc',
        'capacite'            => 100,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_heritage'],
        'plan_salle'          => [
            'rangees'           => 8,
            'sieges_par_rangee' => 12,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440705',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440007',
        'numero'              => '5',
        'nom'                 => 'Salle Saint-Sernin',
        'capacite'            => 80,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_heritage'],
        'plan_salle'          => [
            'rangees'           => 6,
            'sieges_par_rangee' => 13,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],
    [
        'uuid'                => '550e8400-e29b-41d4-a716-446655440706',
        'cinema_uuid'         => '550e8400-e29b-41d4-a716-446655440007',
        'numero'              => '6',
        'nom'                 => 'Salle Jacobins',
        'capacite'            => 60,
        'etat'                => 'active',
        'qualites_projection' => ['standard'],
        'equipements'         => ['fauteuils_heritage'],
        'plan_salle'          => [
            'rangees'           => 5,
            'sieges_par_rangee' => 12,
            'allees'            => 1,
            'pmr'               => 2,
        ],
    ],
];
